import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import {
  Box,
  ChakraProvider,
  Flex,
  Stack,
  Wrap,
  WrapItem,
  Image,
  SimpleGrid,
} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  projects: any[];
};
const Home = () => {
  const [projects, setProjects] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        `https://itp.nyu.edu/projects/public/projectsJSON_ALL.php?venue_id=183`,
        {
          method: "GET",
        }
      );
      const pjs = await response.json();
      setProjects(pjs);
    };
    fetchData();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        padding={4}
        w="100%"
        sx={{ columnCount: [1, 2, 3], columnGap: "8px" }}
      >
        {projects.map((project: any, i) => {
          return (
            <Image
              key={i}
              w="100%"
              borderRadius="xl"
              mb={2}
              display="inline-block"
              src={`https://itp.nyu.edu/${project.image}`}
              alt="Alt"
            />
          );
        })}
      </Box>
    </div>
  );
};
export default Home;
