import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const response = await fetch(
    `https://itp.nyu.edu/projects/public/projectsJSON_ALL.php?venue_id=183`,
    {
      method: "GET",
    }
  );

  const projects = await response.json();
  return {
    props: { projects: projects }, // will be passed to the page component as props
    revalidate: 360, // 1 hour
  };
}
type Props = {
  projects: any[];
};
export default function Home(projects: any[]) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {projects.map((project, i) => {
          return (
            <div key={i}>
              <div>{project.project_name}</div>
              <img src={`https://${project.image}`} />
            </div>
          );
        })}
      </main>
    </>
  );
}
