import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  projects: any[];
};
export default function Home() {
  const [projects, setProjects] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        `https://itp.nyu.edu/projects/public/projectsJSON_ALL.php?venue_id=183`,
        {
          method: "GET",
        }
      );
      const pjs = await response.json();
      setProjects(pjs);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {projects.map((project: any, i) => {
          return (
            <div key={i}>
              <div>{project.project_name}</div>
              <img src={`https://${project.image}`} />
            </div>
          );
        })}
      </main>
    </>
  );
}
